server:
  port: 9909

spring:
  application:
    name: service-aigc

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: qwen2.5:3b
      temperature: 0.8
      timeout: PT60S
    streaming-chat-model:
      base-url: http://localhost:11434
      model-name: gemma3:4b
      temperature: 0.8
      timeout: PT60S
